version: "3.8"
services:
  backend:
    image: mbunce/crud-backend
    build: ./Backend
    container_name: Backend_c
    ports:
      - '8000:8000'
  frontend:
    image: mbunce/crud-frontend
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true